name: easy_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.3.0
  shared_preferences: ^2.2.0
  image_picker: ^0.8.5+3  # 使用最新版本
  intl: ^0.18.1  # 或最新版本
  web_socket_channel: ^2.4.0
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.15
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.0.0+3
  cached_network_image: ^3.2.0
  provider: ^6.0.0
  waterfall_flow: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.0
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
  analyzer: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
